"""Initial Migration

Revision ID: b9ad962d9963
Revises:
Create Date: 2025-04-17 12:16:15.579393

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9ad962d9963"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("abbr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_org_id"), "organization", ["org_id"], unique=True
    )
    op.create_table(
        "recreationarea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_rec_area_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rec_area_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recreationarea_rec_area_id"),
        "recreationarea",
        ["rec_area_id"],
        unique=True,
    )
    op.create_table(
        "facility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("facility_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "activity_pass",
                "archives",
                "campground",
                "cemetary_and_memorial",
                "construction_camp",
                "facility",
                "federal",
                "kiosk",
                "library",
                "museum",
                "fish_hatchery",
                "permit",
                "ticket",
                "timed_entry",
                "tree_permit",
                "reservation",
                "visitor_center",
                name="facilitytype",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("rec_area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rec_area_id"],
            ["recreationarea.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_facility_facility_id"), "facility", ["facility_id"], unique=True
    )
    op.create_index(op.f("ix_facility_name"), "facility", ["name"], unique=False)
    op.create_table(
        "campsite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("loop", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("campsite_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "anchorage",
                "ball_field",
                "boat_in",
                "cabin",
                "designated_campsite",
                "equestrian",
                "hike_to",
                "lookout",
                "management",
                "mooring",
                "overnight_shelter",
                "parking",
                "picnic",
                "rv",
                "shelter",
                "standard",
                "standard_area",
                "tent_only",
                "walk_to",
                "yes",
                "yurt",
                "zone",
                "no_type",
                name="campsitetype",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("electric", sa.Boolean(), nullable=False),
        sa.Column("group_site", sa.Boolean(), nullable=False),
        sa.Column(
            "use",
            sa.Enum(
                "overnight", "day", "multi", name="usetype", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facility.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "division",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["facility.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("division_id"),
    )
    op.create_table(
        "itinerary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("permit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permit_id"],
            ["facility.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lottery",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("lottery_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("desc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "executed", name="lotterystatus"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("queue_lottery", "camping", "ticket", "permit", name="lotterytype"),
            nullable=False,
        ),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.Column("display_at", sa.DateTime(), nullable=False),
        sa.Column("open_at", sa.DateTime(), nullable=False),
        sa.Column("close_at", sa.DateTime(), nullable=False),
        sa.Column("scheduled_run_at", sa.DateTime(), nullable=False),
        sa.Column("ran_at", sa.DateTime(), nullable=False),
        sa.Column("announced_at", sa.DateTime(), nullable=False),
        sa.Column("access_start_at", sa.DateTime(), nullable=False),
        sa.Column("access_end_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facility.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lottery_lottery_id"), "lottery", ["lottery_id"], unique=False
    )
    op.create_index(op.f("ix_lottery_name"), "lottery", ["name"], unique=False)
    op.create_table(
        "ordereditinerarydivision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itinerary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ordereditinerarydivision")
    op.drop_index(op.f("ix_lottery_name"), table_name="lottery")
    op.drop_index(op.f("ix_lottery_lottery_id"), table_name="lottery")
    op.drop_table("lottery")
    op.drop_table("itinerary")
    op.drop_table("division")
    op.drop_table("campsite")
    op.drop_index(op.f("ix_facility_name"), table_name="facility")
    op.drop_index(op.f("ix_facility_facility_id"), table_name="facility")
    op.drop_table("facility")
    op.drop_index(op.f("ix_recreationarea_rec_area_id"), table_name="recreationarea")
    op.drop_table("recreationarea")
    op.drop_index(op.f("ix_organization_org_id"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
